/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package company.management.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Kh. Ahsun Habib
 */
public class EmployeeView extends javax.swing.JFrame {

    public boolean a = false;
    public int id;
    public String name;
    public String email;
    public String branch;
    public String designation;
    public String salary;
    public String gender;

    /**
     * Creates new form LoginView
     */
    public EmployeeView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbDesignation = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        rMale = new javax.swing.JRadioButton();
        rFemale = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cmbBranch = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\My Project\\Logo.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(580, 20, 190, 100);

        jLabel3.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(470, 230, 60, 30);

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 280, 60, 30);
        jPanel1.add(txtID);
        txtID.setBounds(540, 180, 320, 30);
        jPanel1.add(txtName);
        txtName.setBounds(540, 230, 320, 30);

        jLabel5.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(490, 180, 30, 20);

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Branch");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(450, 335, 80, 25);

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(540, 530, 100, 30);

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);
        btnDelete.setBounds(650, 530, 80, 30);

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(740, 530, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Designation");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(400, 380, 120, 20);

        cmbDesignation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CEO", "Team Leader", "General Manager", "Deputy General Manager", "Assistant General Manager", "Marketing Manager", "Branch Manager", "Executive", "Sales Manager", "Director", "Coordinator", "Administrator", "Controller", " ", " " }));
        cmbDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDesignationActionPerformed(evt);
            }
        });
        jPanel1.add(cmbDesignation);
        cmbDesignation.setBounds(540, 380, 320, 30);

        jLabel6.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(450, 480, 71, 30);

        buttonGroup1.add(rMale);
        rMale.setForeground(new java.awt.Color(255, 255, 255));
        rMale.setText("Male");
        rMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rMaleActionPerformed(evt);
            }
        });
        jPanel1.add(rMale);
        rMale.setBounds(540, 480, 70, 23);

        buttonGroup1.add(rFemale);
        rFemale.setForeground(new java.awt.Color(255, 255, 255));
        rFemale.setText("Female");
        rFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rFemaleActionPerformed(evt);
            }
        });
        jPanel1.add(rFemale);
        rFemale.setBounds(620, 480, 80, 23);

        jLabel9.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Salary");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(450, 430, 70, 30);
        jPanel1.add(txtSalary);
        txtSalary.setBounds(540, 430, 320, 30);
        jPanel1.add(txtEmail);
        txtEmail.setBounds(540, 280, 320, 30);

        cmbBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Mymensingh", "Rajshahi", "Rangpur", "Chittagong", "Barisal ", "Sylhet", "Khulna" }));
        cmbBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBranchActionPerformed(evt);
            }
        });
        jPanel1.add(cmbBranch);
        cmbBranch.setBounds(540, 330, 320, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(740, 580, 120, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Add Your Employee Here");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(560, 140, 230, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/company/Final icon/Home Icon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 10, 50, 50);

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setText("Search BY ID");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch);
        btnSearch.setBounds(540, 580, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\My Project\\Background.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1720, 760);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDesignationActionPerformed

    private void cmbBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBranchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:   
        id = Integer.parseInt(txtID.getText());
        name = txtName.getText();
        email = txtEmail.getText();
        branch = cmbBranch.getSelectedItem().toString();
        designation = cmbDesignation.getSelectedItem().toString();
        salary = txtSalary.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/swing_demo", "root", "1234");
            String sq = "INSERT INTO employee" + "(id,name,email,branch,designation,salary,gender)" + "VALUES (?,?,?,?,?,?,?)";
            PreparedStatement st = con.prepareStatement(sq);
            st.setInt(1, id);
            st.setString(2, name);
            st.setString(3, email);
            st.setString(4, branch);
            st.setString(5, designation);
            st.setString(6, salary);
            st.setString(7, gender);
            st.executeUpdate();
            st.close();
            JOptionPane.showMessageDialog(null, "Data Inserted Successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data does not inserted" + e);
        }


    }//GEN-LAST:event_btnAddActionPerformed

    private void rMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rMaleActionPerformed
        // TODO add your handling code here:\
        gender = "Male";
    }//GEN-LAST:event_rMaleActionPerformed

    private void rFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rFemaleActionPerformed
        // TODO add your handling code here:
        gender = "Female";
    }//GEN-LAST:event_rFemaleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DashboardView().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DashboardView().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        id = Integer.parseInt(txtID.getText());
        int p = JOptionPane.showConfirmDialog(null, "Do you want to delete?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/swing_demo", "root", "1234");

                String sq = "delete from employee where  id='" + id + "'";
                Statement st = con.createStatement();
                st.executeUpdate(sq);

                JOptionPane.showMessageDialog(rootPane, "Details Successfully Removed!");
                // JOptionPane.showMessageDialog(null,"Details Successfully Inserted");
            } catch (Exception ee) {
                System.out.println("The error is:" + ee);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        id = Integer.parseInt(txtID.getText());
        name = txtName.getText();
        email = txtEmail.getText();
        branch = cmbBranch.getSelectedItem().toString();
        designation = cmbDesignation.getSelectedItem().toString();
        salary = txtSalary.getText();

        int p = JOptionPane.showConfirmDialog(null, "Do you want to Update Info.?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/swing_demo", "root", "1234");
                String sq = "UPDATE employee SET name ='" + name + "', email ='" + email + "', branch ='" + branch + "', designation = '" + designation + "', salary='" + salary + "' WHERE id = " + id;
                Statement st = con.createStatement();
                st.executeUpdate(sq);
                JOptionPane.showMessageDialog(rootPane, "Data Updated Successfully!");
            } catch (Exception ee) {
                System.out.println("The error is:" + ee);
                
            }

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
            String a = txtID.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/swing_demo", "root", "1234");
            String sql = "select * from employee where  id='" + a + "'";
            Statement st = con.createStatement();
            //pst.setString(1, u);

            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                txtName.setText(rs.getString("name"));
                txtEmail.setText(rs.getString("email"));
                cmbBranch.setSelectedItem(rs.getString("branch"));
                cmbDesignation.setSelectedItem(rs.getString("designation"));
                txtSalary.setText(rs.getString("salary"));

            } else {
                JOptionPane.showMessageDialog(rootPane, "No Data Found!");

            }

        } catch (Exception ex) {
            //Logger.getLogger(RemoveEmployee.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("The error is:" + ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbBranch;
    private javax.swing.JComboBox<String> cmbDesignation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rFemale;
    private javax.swing.JRadioButton rMale;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
