/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package company.management.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Kh. Ahsun Habib
 */
public class ProductPurchaseTableView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public ProductPurchaseTableView() {
        initComponents();
    }
    public int productId;
    public String productName;
    public String productModel;
    public String productSize;
    public String productCategory;
    public int unitPrice;
    public int quantity;
    public int totalPrice;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tPrice = new javax.swing.JTextField();
        pModel = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        pSize = new javax.swing.JTextField();
        uPrice = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        pName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\My Project\\Logo.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(630, 60, 190, 100);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(830, 590, 65, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Product Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 240, 120, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Product Model");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(460, 300, 110, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Product Category");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(440, 400, 130, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Quantity");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(500, 500, 70, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Unit Price");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(500, 450, 70, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Total Price");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(490, 550, 80, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Product Size");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(470, 350, 90, 17);
        jPanel1.add(tPrice);
        tPrice.setBounds(590, 540, 300, 30);
        jPanel1.add(pModel);
        pModel.setBounds(590, 290, 300, 30);

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regregerator and Freezer", "Television", "Mobile", "Computer", "Air Conditioner", "Washing Machine", "Home Appliances", "Fan", "Electrical Appliances", "Elevator", "Compressor", "Generator and Battery", "Solar Street Lamp", "Water Pump", "Industrial Solutions", "Hardware Items" }));
        jPanel1.add(cmbCategory);
        cmbCategory.setBounds(590, 390, 300, 30);
        jPanel1.add(pSize);
        pSize.setBounds(590, 340, 300, 30);
        jPanel1.add(uPrice);
        uPrice.setBounds(590, 440, 300, 30);
        jPanel1.add(qty);
        qty.setBounds(590, 490, 300, 30);
        jPanel1.add(pName);
        pName.setBounds(590, 240, 300, 30);

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(590, 590, 73, 30);

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);
        btnDelete.setBounds(790, 630, 110, 30);

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(680, 590, 140, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Product ID");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(480, 190, 80, 20);
        jPanel1.add(txtID);
        txtID.setBounds(590, 190, 300, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/company/Final icon/Home Icon.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 10, 60, 50);

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setText("Search BY ID");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch);
        btnSearch.setBounds(590, 630, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\My Project\\Background.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1720, 760);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DashboardView().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DashboardView().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            productId = Integer.parseInt(txtID.getText());
            productName = pName.getText();
            productModel = pModel.getText();
            productSize = pSize.getText();
            productCategory = cmbCategory.getSelectedItem().toString();
            unitPrice = Integer.parseInt(uPrice.getText());
            quantity = Integer.parseInt(qty.getText());
            totalPrice = Integer.parseInt(tPrice.getText());

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/swing_demo", "root", "1234");
            String sq = "INSERT INTO store " + "(product_id,product_name,product_Model,product_size,product_category,unit_price,quantity,total_price)" + "VALUES (?,?,?,?,?,?,?,?)";
            PreparedStatement st = con.prepareStatement(sq);
            st.setInt(1, productId);
            st.setString(2, productName);
            st.setString(3, productModel);
            st.setString(4, productSize);
            st.setString(5, productCategory);
            st.setInt(6, unitPrice);
            st.setInt(7, quantity);
            st.setInt(8, totalPrice);
            st.executeUpdate();
            st.close();

            JOptionPane.showMessageDialog(rootPane, "Product Stored in the table!");
        } catch (Exception e) {
            System.out.println("Something Went wrong" + e);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
            String pId = txtID.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/swing_demo", "root", "1234");
            String sql = "select * from store where  product_id ='" + pId + "'";
            Statement st = con.createStatement();
            //pst.setString(1, u);

            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                pName.setText(rs.getString("product_name"));
                pModel.setText(rs.getString("product_Model"));
                pSize.setText(rs.getString("product_size"));
                cmbCategory.setSelectedItem(rs.getString("product_category"));
                uPrice.setText(rs.getString("unit_price"));
                qty.setText(rs.getString("quantity"));
                tPrice.setText(rs.getString("total_price"));

                // Print pri=new Print();
                //pri.setVisible(true);
                // setVisible(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "No Data Found!");

            }

        } catch (Exception ex) {
            //Logger.getLogger(RemoveEmployee.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("The error is:" + ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        productId = Integer.parseInt(txtID.getText());
        productName = pName.getText();
        productModel = pModel.getText();
        productSize = pSize.getText();
        productCategory = cmbCategory.getSelectedItem().toString();
        unitPrice = Integer.parseInt(uPrice.getText());
        quantity = Integer.parseInt(qty.getText());
        totalPrice = Integer.parseInt(tPrice.getText());

        int p = JOptionPane.showConfirmDialog(null, "Do you want to Update Info.?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/swing_demo", "root", "1234");
                String sq = "UPDATE store SET product_name ='" + productName + "', product_model ='" + productModel + "', product_size ='" + productSize + "', product_category = '" + productCategory + "', unit_price ='" + unitPrice + "', quantity= '" + quantity + "', total_price = '" + totalPrice + "' WHERE product_id = " + productId;
                Statement st = con.createStatement();
                st.executeUpdate(sq);
                JOptionPane.showMessageDialog(rootPane, "Product Updated Successfully!");
            } catch (Exception ee) {
                System.out.println("The error is:" + ee);

            }

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        productId = Integer.parseInt(txtID.getText());
        int p = JOptionPane.showConfirmDialog(null, "Do you want to delete?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/swing_demo", "root", "1234");

                String sq = "delete from store where  product_id='" + productId + "'";
                Statement st = con.createStatement();
                st.executeUpdate(sq);

                JOptionPane.showMessageDialog(rootPane, "Product Successfully Deleted!");

            } catch (Exception ee) {
                System.out.println("The error is:" + ee);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductPurchaseTableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductPurchaseTableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductPurchaseTableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductPurchaseTableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductPurchaseTableView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pModel;
    private javax.swing.JTextField pName;
    private javax.swing.JTextField pSize;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField tPrice;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField uPrice;
    // End of variables declaration//GEN-END:variables
}
